### ISSUE TITLE
Handle bollards and node-based restrictions

### ISSUE THREAD

**Issue by xivk** [openplannerteam/routable-tiles#14]
In the spec we don't have a way to handle node-based restrictions yet:

https://www.openstreetmap.org/node/560782706#map=19/50.99149/4.82946

**Comment by xivk** [comment]
Suggested solution is to include the needed tags at the node level:

https://github.com/openplannerteam/website/blob/specification-v1/_specs/2018-11-routable-tiles.html#L155

**Comment by pietercolpaert** [comment]
Makes sense!

**Comment by xivk** [comment]
And so shall it be! :+1:

**Comment by xivk** [comment]
Updated spec:

https://github.com/openplannerteam/website/commit/a999f98d2e5e81f21443f4efc633ced158d9ea8f

**Comment by xivk** [comment]
This is done, this tile:

https://tiles.openplanner.team/planet/14/8411/5485/

Now contains this node:

https://www.openstreetmap.org/node/560782706
