### ISSUE TITLE
Update the tiles with proper IDs

### ISSUE THREAD

**Issue by xivk** [openplannerteam/routable-tiles#2]
Update the tiles with IDs sourced from OSM and combine them with a tile ID. Once we have them in Itinero we can do this.

**Comment by xivk** [comment]
#3 first.

**Comment by pietercolpaert** [comment]
Awesome!

**Comment by xivk** [comment]
Sorry need to reopen:

- [ ] The ID's are not as stable as they can be at the moment, we also need to include the version # of the nodes.

**Comment by xivk** [comment]
Started work on this [here](https://github.com/itinero/routing/commits/features/keep-node-versions). We need to refactor the code loading the OSM data a bit so node versions can be stored in the second pass.

**Comment by xivk** [comment]
This has become obsolete because of:

https://github.com/openplannerteam/website/tree/specification-v1
and
https://github.com/openplannerteam/routable-tiles/milestone/2
