### ISSUE TITLE
Consider adding a @type to the nodes in the tile data

### ISSUE THREAD

**Issue by hdelva** [openplannerteam/routable-tiles#24]
We currently define nodes like this:
```json
{
  "@id":"http://www.openstreetmap.org/node/31366201",
  "geo:long":3.7202407,
  "geo:lat":51.0346015
}
```

Which is fine, the OSM wiki says everything with a longtitude/latitude pair is a node. Still though, I'd recommend adding the type explicitly. This would make filtering more clean and it would make the data more machine-friendly. Definitions on a wiki seem like more of a human thing. 

Adding an @type to all ~3000 nodes in https://tiles.openplanner.team/planet/14/8361/5482/ increases the plaintext file size from 706kb to 808kb, but it only raises the compressed file size from 81kb to 82kb. I think having cleaner data is worth the extra 1% larger files.

**Comment by xivk** [comment]
We can still do this, I will change the nodes to this:

```json
{
  "@id":"http://www.openstreetmap.org/node/31366201",
  "@type": "osm:Node",
  "geo:long":3.7202407,
  "geo:lat":51.0346015
}
```
