### ISSUE TITLE
'Cannot store weight for .... way_id=115513871'

### ISSUE THREAD

**Issue by pietervdvn** [openplannerteam/routable-tiles#36]
When thoroughly testing itinero-transit, I had these warnings pop up a few times (although it did not crash the calculation):

`Cannot store weight for bicycle=yes|foot=yes|access=private|highway=path|tile_x=8406|tile_y=5517|way_id=115513871: > 16777216`

I suspect that the way_id is to big to save, as it is bigger then 2^24

**Comment by pietervdvn** [comment]
Note: this was tested with version pre33

**Comment by xivk** [comment]
This has no impact on the calculations, just on performance. It's a warning that the layout doesn't provide enough space for the weight on this edge. It will just calculate the edge weight on the fly when that one edge is hit.

This will be changed in the future.

**Comment by pietervdvn** [comment]
Allright, I'll won't worry about it then
